config/routes.rb
Rails.application.routes.draw do
  root 'home#welcome'

  namespace :api, defaults: { format: 'json' } do

    resources :products, only: [:create, :show, :index, :update] do
      resources :plans, only: [:index]
    end
    resources :plans, only: [:create, :show, :index, :update] do
      resources :prices, only: :index
    end
    resources :prices, only: [:show, :create]
    resources :periodicities, only: [:create, :index, :update, :show]
  end

  resources :products, only: [:new, :create, :show, :edit, :update]
  resources :plans, only: [:new, :create, :show, :edit, :update]
end

app/models/periodicity.rb
class Periodicity < ActiveRecord::Base
  has_many :prices
  has_many :plan, through: :prices

  validates :name, :deadline, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :product
  has_many :prices
  has_many :periodicities, through: :prices

  serialize :details, Array

  validates :name, :description, :product, presence: true

  def valid_prices
    prices.group_by(&:periodicity_id).map { |p| p[1].max }
  end
end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :plan
  belongs_to :periodicity

  validates :plan, :periodicity, :value, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :plans

  mount_uploader :image, ImageUploader

  validates :name, :description, presence: true
end

app/controllers/api/.#api_controller.rb
joao@joao-PC.13832:1456611119

app/controllers/api/api_controller.rb
require 'application_responder'

module Api
  class ApiController < ApplicationController
    respond_to :json
  end
end

app/controllers/api/periodicities_controller.rb
module Api
  class PeriodicitiesController < ApiController
    def create
      @periodicity = Periodicity.create(periodicity_params)
      respond_with :api, @periodicity
    end

    def show
      @periodicity = Periodicity.find(params[:id])
      respond_with @periodicity
    end

    def index
      @periodicities = Periodicity.all
      respond_with @periodicities
    end

    def update
      @periodicity = Periodicity.find(params[:id])
      @periodicity.update(periodicity_params)
      respond_with @periodicity
    end

    private

    def periodicity_params
      params.require(:periodicity).permit(:name, :deadline)
    end
  end
end

app/controllers/api/plans_controller.rb
module Api
  class PlansController < ApiController
    def index
      @plans = Plan.where(product_id: params[:product_id]).map do |plan|
        PlanDecorator.new(plan)
      end
      respond_with @plans.map { |plan| plan.to_json('prices_path') }
    end

    def show
      @plan = PlanDecorator.new(Plan.find(params[:id])).to_json
      respond_with @plan
    end

    def create
      @plan = Plan.create(plan_params)
      respond_with :api, @plan
    end

    def update
      @plan = Plan.find(params[:id])
      @plan.update(plan_params)
      respond_with @plan
    end

    private

    def plan_params
      params.require(:plan).permit(:name,
                                   :description,
                                   :product_id,
                                   details: [])
    end
  end
end

app/controllers/api/prices_controller.rb
module Api
  class PricesController < ApiController
    before_action :set_plan, only: [:index, :create]

    def create
      @periodicity = Periodicity.find(params[:periodicity_id])
      @price = Price.create(plan_id: @plan.id,
                            periodicity_id: @periodicity.id,
                            value: params[:value])
      respond_with :api, @price
    end

    def show
      @price_decorated = PriceDecorator.new(Price.find(params[:id])).to_json
      respond_with @price_decorated
    end

    def index
      @periodicities = @plan.periodicities
      @prices = @periodicities.map do |periodicity|
        PeriodicityDecorator.new(periodicity, @plan)
      end
      respond_with @prices.map(&:to_json)
    end

    def set_plan
      @plan = Plan.find(params[:plan_id])
    end
  end
end

app/controllers/api/products_controller.rb
module Api
  class ProductsController < ApiController
    def create
      @product = Product.create(product_params)
      respond_with :api, @product
    end

    def index
      @products = Product.all
      respond_with @products
    end

    def show
      @product_decorated = ProductDecorator.new(Product.find(params[:id]))
      respond_with @product_decorated.to_json
    end

    def update
      @product = Product.find(params[:id])
      @product.update(product_params)
      respond_with @product
    end

    private

    def product_params
      params.require(:product).permit(:name, :description, :image)
    end
  end
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update]
  before_action :set_periodicities, only: [:edit, :update]
  before_action :set_resources, only: [:edit, :update]
  def new
    @products = Product.all
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    save_details @plan
    respond_with @plan
  end

  def show
  end

  def edit
    @price = @plan.prices.build
  end

  def update
    @plan.update(plan_params)
    price_create(@plan)
    save_details @plan
    respond_with @plan
  end

  private

  def set_periodicities
    @periodicities = Periodicity.all
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def set_resources
    @periodicities = Periodicity.all
  end

  def plan_params
    params.require(:plan).permit(:name, :description,
                                 :product_id, details: [])
  end

  def price_params
    params.require(:plan).permit(prices: [:periodicity_id, :value])
  end

  def save_details(plan)
    plan.details = params[:plan][:details]
                   .map { |detail| detail } if params[:plan][:details]
    plan.save
  end

  def price_create(plan)
    plan.prices.create(periodicity_id: price_params[:prices][:periodicity_id],
                       value: price_params[:prices][:value]) if
                         price_params[:prices][:value].present?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    respond_with @product
  end

  def show
    @product = Product.find(params[:id])
    respond_with @product
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    respond_with @product
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/welcome.html.erb
<pre>
  {
    "api_product_plans_path": "/products/{product_id}/plans",

    "api_products_path":      "/products",

    "api_product_path":       "/products/{product_id}",

    "api_plans_path":         "/plans",

    "api_plan_path":          "/plans/{plan_id}",

    "api_plan_prices":        "/api/plans/{plan_id}/prices"

    "api_price_path":         "/prices/{price_id}",

    "api_periodicities_path": "/periodicities",

    "api_periodicity_path":   "/periodicities/{periodicity_id}"
  }
</pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="ls-theme-green">
<head>
  <title>PlanProductApi</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <meta name="description" content="Sistema de Vendas CampusCode.">
  <link href="http://assets.locaweb.com.br/locastyle/3.8.2/stylesheets/locastyle.css" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

</head>
<body>
  <div class="ls-topbar ">

    <!-- Barra de Notificações -->
    <div class="ls-notification-topbar">

      <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
        <a href="#" class="ls-ico-user">
          <span class="ls-name"></span>
        </a>

        <nav class="ls-dropdown-nav ls-user-menu">
          <ul>
            <li></li>
            <li></li>
           </ul>
        </nav>
      </div>
    </div>

    <span class="ls-show-sidebar ls-ico-menu"></span>

    <%= link_to :back, class: 'ls-go-next' do %>
      <span class="ls-text">Voltar à lista de serviços</span>
    <% end %>

    <!-- Nome do produto/marca com sidebar -->
    <h1 class="ls-brand-name">
      <a href="/" class="ls-ico-earth">
        <small>CampusCode</small>
        Venda de Produtos
      </a>
    </h1>

    <!-- Nome do produto/marca sem sidebar quando for o pre-painel  -->
    </div>


    <aside class="ls-sidebar">

    <div class="ls-sidebar-inner">
      <a href="/locawebstyle/documentacao/exemplos//pre-painel"  class="ls-go-prev"><span class="ls-text">Voltar à lista de serviços</span></a>

      <nav class="ls-menu">
        <ul>
          <li></li>
          <li></li>
          <li></li>
          <li> </li>
          <li></li>
        </ul>
      </nav>


    </div>
    </aside>

    <main class="ls-main ">
      <div class="container-fluid">
        <span class="ls-alert-warning col-xs-12"><%= flash[:alert] %></span>
        <span class="ls-alert-success col-xs-12"><%= flash[:notice] %></span>
        <%= yield %>
      </div>
    </main>

    <!-- We recommended use jQuery 1.10 or up -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="http://assets.locaweb.com.br/locastyle/3.8.2/javascripts/locastyle.js" type="text/javascript"></script>

</body>
</html>

app/views/plans/edit.html.erb
<h2 class="ls-title-intro ls-ico-user"><%= t('edit_plan') %> <%= @plan.name %></h2>
<hr>
<% if @plan.errors.any? %>
  <ul>
    <% @plan.errors.full_messages.each do |error|%>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<section id="customer_form">
<%= simple_form_for @plan do |f| %>
  <div class="form-inputs">
    <label class="ls-label col-md-3">
      <%= f.input :name, required: true,
                         autofocus: true,
                         class: 'ls-login-bg-user ls-field-lg',
                         error_html: { class: 'ls-success ls-help-message'}  %>
    </label>
    <label class="ls-label col-md-3">
      <%= f.input :description, required: true,
                                class: 'ls-login-bg-user ls-field-lg',
                                error_html: { class: 'ls-success ls-help-message'}  %>
    </label>

    <div class="input_fields_wrap">
      <div>
        <label class="ls-label col-md-3">
          <label class="text required control-label">
            <%= t('activerecord.attributes.plan.details') %> <button class="add_field_button ls-btn-primary" id="detalhe">+</button>
          </label>
          <%= f.input :details, label: false, as: :array %>
        </label>
      </div>
    </div>

    <label class="ls-label col-md-3">
      <b class="ls-label-text"><%= t('activerecord.attributes.plan.product') %></b>
      <div class="ls-custom-select">
          <%= f.input_field :product_id, collection: @products, prompt: :translate, class: "ls-custom-select" %>
      </div>
    </label>


    <%= f.simple_fields_for :prices do |price| %>
      <label class="ls-label col-md-3">
        <h3><%= t('insert_price') %></h3>
        <br>
        <div class="ls-custom-select">

          <%= price.input_field :periodicity_id, label: t('activerecord.attributes.price.periodicity_id'), collection: @periodicities,
                                           prompt: t('activerecord.attributes.price.periodicity_id') %>
        </div>
      </label>
      <label class="ls-label col-md-3">
        <%= price.input :value, label: t('activerecord.attributes.price.value') %>
      </label>
    <% end %>
    <div class="form-actions">
      <%= f.submit class: 'ls-btn-primary ls-btn-block ls-btn-lg' %>
    </div>
    <p><%= link_to t('back'), :back %></p>
  <% end %>
</div>

app/views/plans/new.html.erb
<h2 class="ls-title-intro ls-ico-user"><%= t('create_plan') %></h2>

<% if @plan.errors.any? %>
  <ul>
  <% @plan.errors.full_messages.each do |error|%>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

<section id="customer_form">
  <%= simple_form_for @plan do |f| %>

    <div class="form-inputs">
      <label class="ls-label col-md-3">
        <%= f.input :name %>
      </label>

      <label class="ls-label col-md-3">
        <%= f.input :description %>
      </label>

        <div class="input_fields_wrap">
          <div>
            <label class="ls-label col-md-3">
              <label class="text required control-label"><%= t('activerecord.attributes.plan.details') %> <button class="add_field_button ls-btn-primary" id="detalhe">+</button></label>
            </label>
          </div>
        </div>

        <label class="ls-label col-md-3">
          <b class="ls-label-text"><%= t('activerecord.attributes.plan.product') %></b>
          <div class="ls-custom-select">
              <%= f.input_field :product_id, collection: @products, prompt: :translate, class: "ls-custom-select" %>
          </div>
        </label>

        <div class="form-actions">
          <%= f.submit class: 'ls-btn-primary ls-btn-block ls-btn-lg' %>
        </div>
      <% end %>
  </div>
</section>

app/views/plans/show.html.erb
<h2 class="ls-title-intro ls-ico-user"><%= t('show_plan') %></h2>

<span>
  <h3><%= @plan.name %></h3>
  <hr>
  <p><strong><%= t('activerecord.attributes.plan.description') %>: </strong> <%= @plan.description %></p>
  <p><strong><%= t('activerecord.attributes.plan.product') %>: </strong> <%= @plan.product.name %></p>

  <div class='group'>
    <p><strong><%= t('activerecord.attributes.plan.details') %>:</strong></p>
    <ul>
      <% @plan.details.each do |detail| %>
      <li><%= detail %></li>
      <% end %>
    </ul>
  </div>

<div class='group'>
  <h4><%= t('prices') %>:</h4>
  <% @plan.valid_prices.each do |price| %>
    <p><%= price.periodicity.name %><br>
       <%= price.value %></p>
  <% end %>
</div>

  <p><%= link_to t('back'), :back %>
     <%= link_to t('edit_plan'), edit_plan_path(@plan) %></p>

</span>

app/views/products/_form.html.erb
<section id="customer_form">
  <%= simple_form_for @product do |f| %>
    <div class="form-inputs">
        <label class="ls-label col-md-3">
          <%= f.input :name, required: true,
                             autofocus: true,
                             class: 'ls-login-bg-user ls-field-lg',
                             error_html: { class: 'ls-success ls-help-message'}  %>
        </label>

        <label class="ls-label col-md-3">
          <%= f.input :description, required: true,
                                    class: 'ls-login-bg-user ls-field-lg',
                                    error_html: { class: 'ls-success ls-help-message'}  %>
        </label>

        <label class="ls-label col-md-3">
          <%= f.label :image, class: 'ls-login-bg-user ls-field-lg' %><br/>
          <%= f.file_field :image %><br>
        </label>

        <div class="form-actions">
          <%= f.button :submit, class: 'ls-btn-primary ls-btn-block ls-btn-lg' %>
        </div>
      <% end %>
    </div>

</section>

app/views/products/edit.html.erb
<h2 class="ls-title-intro ls-ico-user"><%= t('edit_product') %></h2>
<%= render 'form' %>

app/views/products/new.html.erb
<h2 class="ls-title-intro ls-ico-user"><%= t('create_product') %></h2>
<%= render 'form' %>

app/views/products/show.html.erb
<h2 class="ls-title-intro ls-ico-user"><%= t('show_product') %></h2>

<span>
  <h3><%= @product.name %></h3>
  <hr>
  <p><strong><%= t('activerecord.attributes.product.description') %>: </strong><%= @product.description %></p>
  <p><%= image_tag @product.image %></p>
</span>